name: Cloud integration test splitter
description: Evaluate pull request size.

inputs:
  path:
    description: The path to the collection.
    required: true

runs:
  using: composite
  steps:
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install python required libraries
      run: pip install -U requests
      shell: bash

    - name: Evaluate pull request size
      run: >-
        python3 ${{ github.action_path }}/check_pr.py
        --path ${{ inputs.path }}
        --repository ${{ github.repository }}
        --pr-number ${{ github.event.pull_request.number }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.GITHUB_TOKEN }}
