name: Run AWX docker-compose
description: Runs AWX with `make docker-compose`
inputs:
  python_version:
    description: The python version to use for awx
    required: false
    default: '3.10'
outputs:
  admin:
    description: The username used to connect to awx
    value: 'admin'
  password:
    description: The user password used to connect to awx
    value: 'test123'

runs:
  using: composite
  steps:
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: "${{ inputs.python_version }}"

    - name: Install ansible-core
      run: python3 -m pip install ansible-core
      shell: bash

    - name: Get python version from Makefile
      shell: bash
      run: echo py_version=`make PYTHON_VERSION` >> $GITHUB_ENV

    - name: Clone required awx version
      uses: actions/checkout@v4
      with:
        repository: gravesm/awx

    - name: Build image for current source checkout
      shell: bash
      run: |
        make docker-compose-build

    - name: Install system deps
      shell: bash
      run: sudo apt-get install -y gettext

    - name: Start AWX
      shell: bash
      run: COMPOSE_UP_OPTS="-d" make docker-compose

    - name: Update default AWX password
      shell: bash
      run: |
        while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' -k https://localhost:8043/api/v2/ping/)" != "200" ]]
        do
        echo "Waiting for AWX..."
        sleep 5
        done
        echo "AWX is up, updating the password..."
        docker exec -i tools_awx_1 sh <<-EOSH
          awx-manage update_password --username=admin --password=test123
        EOSH