---
name: acceptance tests

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        go_version: '1.21.1'

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go ${{ env.go_version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.go_version }}

      - name: Install dependencies
        run: go get .

      - name: Build
        run: go build -v ./...

      - name: Build awx_devel image for running checks
        id: run-awx
        uses: ./.github/actions/run_awx
  
      - name: List job templates resources
        run: curl -k -u '${{ steps.run-awx.outputs.admin }}:${{ steps.run-awx.outputs.password }}' https://localhost:8043/api/v2/job_templates/

      - name: Run unit tests
        run: make testacc
