name: Code review
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main
      - stable-*

jobs:
  pull-request-size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./github/actions/size_pull_request
        with:
            path: "."