name: Code review
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main
      - stable-*

jobs:
  pull-request-size:
    runs-on: ubuntu-latest
    permissions:
        pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - uses: abikouo/terraform-provider-aap/.github/actions/size_pull_request@size_pr_aap_version
        with:
            path: "."