name: unit tests

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        go_version: '1.21.1'

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go ${{ env.go_version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.go_version }}

      - name: Install dependencies
        run: go get .

      - name: Build
        run: go build -v ./...

      - name: Run unit tests
        run: go test -v ./...
